/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-03-01 12:30:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.house;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class search_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/project/SsangYongBangProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/SsangYongBang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1613534080129L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1614528299152L));
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1614146715570L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1613455475942L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>방 찾기</title>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sybang/asset/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sybang/css/main.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/sybang/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/sybang/asset/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"/sybang/asset/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sybang/css/house.css\">\r\n");
      out.write("<!-- 토글 스위치 참조 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sybang/asset/css/switchery.css\">\r\n");
      out.write("<script src=\"/sybang/asset/js/switchery.js\"></script>\r\n");
      out.write("<!-- jquery-ui 참조 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sybang/asset/css/jquery-ui.css\">\r\n");
      out.write("<script src=\"/sybang/asset/js/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.6.1/css/all.css\"\r\n");
      out.write("        integrity=\"sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"//developers.kakao.com/sdk/js/kakao.min.js\"></script> \r\n");
      out.write("<style>\r\n");
      out.write(".modal-open{overflow:auto;padding-right:0 !important;}\r\n");
      out.write(".infowindow a {color:#486BB8;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- header 가져오기######## -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t/* house.css와 width, padding 충돌 */\r\n");
      out.write("\t.header-cklee .dropdown, .dropdown-menu {\r\n");
      out.write("\t    width: auto;\r\n");
      out.write("\t    padding: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-cklee\">\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-static-top\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"/sybang/index.do\">\r\n");
      out.write("\t\t\t\t<img alt=\"Brand\" src=\"/sybang/images/logo.png\" id=\"logo\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/sybang/index.do\">홈</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/sybang/house/search.do\">방찾기</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/sybang/hope/post.do\">희망입주하기</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/sybang/house/post.do\">방내놓기</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">커뮤니티<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t          \t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t            <li><a href=\"/sybang/notice/list.do\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t            <li><a href=\"/sybang/free/list.do\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t         \t</ul>\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"/sybang/broker/brokerMain.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">중개사공간<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t          \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"/sybang/service/servicemain.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">청소/시공<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t          \t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t<!-- 로그인 전 -->\r\n");
      out.write("        \t\t\t");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t<!-- 로그인 후 -->\r\n");
      out.write("        \t\t\t");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> <!-- container-fluid -->\r\n");
      out.write("\t</nav> <!-- navbar -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {    \r\n");
      out.write("\t  $('.navbar-default .navbar-nav > li.dropdown').hover(function() {\r\n");
      out.write("\t\t$('ul.dropdown-menu', this).stop(true, true).slideDown('fast');\r\n");
      out.write("\t\t$(this).addClass('open');\r\n");
      out.write("\t  }, function() {\r\n");
      out.write("\t\t$('ul.dropdown-menu', this).stop(true, true).slideUp('fast');\r\n");
      out.write("\t\t$(this).removeClass('open');\r\n");
      out.write("\t  });\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- list-container 시작 -->\r\n");
      out.write("    <div class=\"list-container\">\r\n");
      out.write("\r\n");
      out.write("        <!-- search-box 시작 -->\r\n");
      out.write("        <div class=\"search-box\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- form 태그 시작 -->\r\n");
      out.write("            <form method=\"POST\" action=\"/sybang/house/searchok.do\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!-- dealtype 시작 -->\r\n");
      out.write("                <div class=\"col-md-6 dealtype\">\r\n");
      out.write("                    <h2 class=\"title\">거래 유형</h2>\r\n");
      out.write("                    <div class=\"btn-group\" data-toggle=\"buttons\" id=\"dType\" name=\"dType\">\r\n");
      out.write("\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 130px; font-size: 1.2em;\">\r\n");
      out.write("                        \t<input type=\"checkbox\" value=\"매매\" name=\"dType\">매매</label>\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 130px; font-size: 1.2em;\">\r\n");
      out.write("                        <input type=\"checkbox\" value=\"전세\" name=\"dType\">전세</label>\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 130px; font-size: 1.2em;\">\r\n");
      out.write("                        <input type=\"checkbox\" value=\"월세\" name=\"dType\">월세</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- dealtype 끝 -->\r\n");
      out.write("\r\n");
      out.write("                <!-- address 시작 -->\r\n");
      out.write("                <div class=\"col-md-6 address\">\r\n");
      out.write("                    <h2 class=\"title\">지역</h2>\r\n");
      out.write("                    <select class=\"form-control\" style=\"width: 130px; padding: 5px; font-size: 1.2em;\" id=\"sido\">\r\n");
      out.write("                        <option value=\"\">시/도</option>\r\n");
      out.write("                        <option value=\"서울\">서울특별시</option>\r\n");
      out.write("                        <option value=\"부산광역시\">부산광역시</option>\r\n");
      out.write("                        <option value=\"대구광역시\">대구광역시</option>\r\n");
      out.write("                        <option value=\"인천광역시\">인천광역시</option>\r\n");
      out.write("                        <option value=\"광주광역시\">광주광역시</option>\r\n");
      out.write("                        <option value=\"경기도\">경기도</option>\r\n");
      out.write("                        <option value=\"강원도\">강원도</option>\r\n");
      out.write("                        <option value=\"충청북도\">충청북도</option>\r\n");
      out.write("                        <option value=\"충청남도\">충청남도</option>\r\n");
      out.write("                        <option value=\"전라북도\">전라북도</option>\r\n");
      out.write("                        <option value=\"전라남도\">전라남도</option>\r\n");
      out.write("                        <option value=\"경상북도\">경상북도</option>\r\n");
      out.write("                        <option value=\"경상남도\">경상남도</option>\r\n");
      out.write("                        <option value=\"제주\">제주특별자치도</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <select class=\"form-control\" style=\"width: 120px; padding: 5px; font-size: 1.2em;\" id=\"gungoo\">\r\n");
      out.write("                        <option value=\"\">시/군/구</option>\r\n");
      out.write("                        <option value=\"강남구\">강남구</option>\r\n");
      out.write("                        <option value=\"강동구\">강동구</option>\r\n");
      out.write("                        <option value=\"강북구\">강북구</option>\r\n");
      out.write("                        <option value=\"강서구\">강서구</option>\r\n");
      out.write("                        <option value=\"관악구\">관악구</option>\r\n");
      out.write("                        <option value=\"광진구\">광진구</option>\r\n");
      out.write("                        <option value=\"구로구\">구로구</option>\r\n");
      out.write("                        <option value=\"금천구\">금천구</option>\r\n");
      out.write("                        <option value=\"노원구\">노원구</option>\r\n");
      out.write("                        <option value=\"도봉구\">도봉구</option>\r\n");
      out.write("                        <option value=\"동대문구\">동대문구</option>\r\n");
      out.write("                        <option value=\"동작구\">동작구</option>\r\n");
      out.write("                        <option value=\"마포구\">마포구</option>\r\n");
      out.write("                        <option value=\"서대문구\">서대문구</option>\r\n");
      out.write("                        <option value=\"서초구\">서초구</option>\r\n");
      out.write("                        <option value=\"성동구\">성동구</option>\r\n");
      out.write("                        <option value=\"성북구\">성북구</option>\r\n");
      out.write("                        <option value=\"송파구\">송파구</option>\r\n");
      out.write("                        <option value=\"양천구\">양천구</option>\r\n");
      out.write("                        <option value=\"영등포구\">영등포구</option>\r\n");
      out.write("                        <option value=\"용산구\">용산구</option>\r\n");
      out.write("                        <option value=\"은평구\">은평구</option>\r\n");
      out.write("                        <option value=\"종로구\">종로구</option>\r\n");
      out.write("                        <option value=\"중구\">중구</option>\r\n");
      out.write("                        <option value=\"중랑구\">중랑구</option>\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <select class=\"form-control\" style=\"width: 120px; padding: 5px; font-size: 1.2em;\" id=\"dong\">\r\n");
      out.write("                        <option value=\"\">읍/면/동</option>\r\n");
      out.write("                        <option value=\"개포동\">개포동</option>\r\n");
      out.write("                        <option value=\"논현동\">논현동</option>\r\n");
      out.write("                        <option value=\"대치동\">대치동</option>\r\n");
      out.write("                        <option value=\"도곡동\">도곡동</option>\r\n");
      out.write("                        <option value=\"삼성동\">삼성동</option>\r\n");
      out.write("                        <option value=\"세곡동\">세곡동</option>\r\n");
      out.write("                        <option value=\"수서동\">수서동</option>\r\n");
      out.write("                        <option value=\"신사동\">신사동</option>\r\n");
      out.write("                        <option value=\"압구정동\">압구정동</option>\r\n");
      out.write("                        <option value=\"역삼동\">역삼동</option>\r\n");
      out.write("                        <option value=\"율현동\">율현동</option>\r\n");
      out.write("                        <option value=\"일원동\">일원동</option>\r\n");
      out.write("                        <option value=\"자곡동\">자곡동</option>\r\n");
      out.write("                        <option value=\"청담동\">청담동</option>\r\n");
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- address 끝 -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!-- buildingtype 시작 -->\r\n");
      out.write("                <div class=\"col-md-6 buildingtype\">\r\n");
      out.write("                    <h2 class=\"title\">건물 종류</h2>\r\n");
      out.write("                    <div class=\"btn-group\" data-toggle=\"buttons\" id=\"bType\" name=\"bType\">\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 95px; font-size: 1.2em;\"><input type=\"checkbox\" value=\"아파트\">아파트</label>\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 100px; font-size: 1.2em;\"><input type=\"checkbox\" value=\"빌라', '주택\">빌라/주택</label>\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 100px; font-size: 1.2em;\"><input type=\"checkbox\" value=\"원룸', '투룸\">원룸/투룸</label>\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 95px; font-size: 1.2em;\"><input type=\"checkbox\" value=\"오피스텔\">오피스텔</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- buildingtype 끝 -->\r\n");
      out.write("\r\n");
      out.write("                <!-- area 시작 -->\r\n");
      out.write("                <div class=\"col-md-6 area\">\r\n");
      out.write("                    <h2 class=\"title\">면적</h2>\r\n");
      out.write("                    <button class=\"btn btn-default modal-button\" type=\"button\" data-toggle=\"modal\"\r\n");
      out.write("                        data-target=\"#areamodal\" style=\"width: 390px; font-size: 1.2em;\">\r\n");
      out.write("                        === 면적을 설정하시려면 클릭하세요 ===\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                    <!-- modal -->\r\n");
      out.write("                    <div class=\"modal fade\" role=\"diaglog\" id=\"areamodal\" data-keyboard=\"true\">\r\n");
      out.write("                        <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                                <div class=\"modal-header\">\r\n");
      out.write("                                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                    <h3 class=\"modal-title\" style=\"text-align: center; font-size: 1.4em;\">면적을 설정하고 적용을 눌러주세요.</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- 방 크기/전용 면적 -->\r\n");
      out.write("                                <div class=\"modal-header\">\r\n");
      out.write("                                    <h3 class=\"modal-title\" style=\"font-size: 1.2em;\">방 크기/전용 면적</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <small style=\"width: 180px; margin-right: 10px;\">\r\n");
      out.write("                                        <div id=\"slider0value1\" class=\"value\" style=\"font-size: 1.2em;\"></div> ㎡ ~\r\n");
      out.write("                                        <div id=\"slider0value2\" class=\"value\" style=\"font-size: 1.2em;\"></div> ㎡\r\n");
      out.write("                                    </small>\r\n");
      out.write("                                    <div id=\"slider0\" class=\"sliders\" style=\"width: 300px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- 방 크기/전용 면적 끝 -->\r\n");
      out.write("                                <div class=\"modal-footer\" style=\"margin-top: 40px;\">\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-success\" id=\"area\" data-dismiss=\"modal\">적용</button>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- modal 끝 -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- area 끝 -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <!-- roomnum 시작 -->\r\n");
      out.write("                <div class=\"col-md-6 roomnum\">\r\n");
      out.write("                    <h2 class=\"title\">방 개수</h2>\r\n");
      out.write("                    <div class=\"btn-group\" data-toggle=\"buttons\" id=\"roomNum\" name=\"roomNum\">\r\n");
      out.write("\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 130px; font-size: 1.2em;\"><input type=\"checkbox\" value=\"1\">1개</label>\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 130px; font-size: 1.2em;\"><input type=\"checkbox\" value=\"2', '3', '4\">2~4개</label>\r\n");
      out.write("                        <label class=\"btn btn-default\" style=\"width: 130px; font-size: 1.2em;\"><input type=\"checkbox\" value=\"5', '6', '7', '8\">5개 이상</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- roomnum 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- price 시작 -->\r\n");
      out.write("                <div class=\"col-md-6 price\">\r\n");
      out.write("                    <h2 class=\"title\">가격대</h2>\r\n");
      out.write("                    <button class=\"btn btn-default modal-button\" type=\"button\" data-toggle=\"modal\"\r\n");
      out.write("                        data-target=\"#pricemodal\" style=\"width: 390px; font-size: 1.2em;\">\r\n");
      out.write("                        === 가격을 설정하시려면 클릭하세요 ===\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("                    <!-- modal -->\r\n");
      out.write("                    <div class=\"modal fade\" role=\"diaglog\" id=\"pricemodal\" data-keyboard=\"true\">\r\n");
      out.write("                        <div class=\"modal-dialog\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                                <div class=\"modal-header\">\r\n");
      out.write("                                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                    <h3 class=\"modal-title \" style=\"text-align: center; font-size: 1.4em;\">가격을 설정하고 적용을 눌러주세요.</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- 보증금/전세가 -->\r\n");
      out.write("                                <div class=\"modal-header\">\r\n");
      out.write("                                    <h3 class=\"modal-title\">보증금/전세가/매매가</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <small style=\"width: 180px;\">\r\n");
      out.write("                                        <div id=\"slider1value1\" class=\"value\"></div> 만원&nbsp;~\r\n");
      out.write("                                        <div id=\"slider1value2\" class=\"value\"></div>&nbsp;&nbsp; 만원\r\n");
      out.write("                                    </small>\r\n");
      out.write("                                    <div id=\"slider1\" class=\"sliders\" style=\"width: 300px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- 보증금/전세가 끝 -->\r\n");
      out.write("\r\n");
      out.write("                                <!-- 월세 -->\r\n");
      out.write("                                <div class=\"modal-header\">\r\n");
      out.write("                                    <h3 class=\"modal-title\">월세</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"modal-body\">\r\n");
      out.write("                                    <small style=\"width: 180px;\">\r\n");
      out.write("                                        <div id=\"slider2value1\" class=\"value\"></div> 만원 ~\r\n");
      out.write("                                        <div id=\"slider2value2\" class=\"value\"></div>&nbsp;&nbsp; 만원\r\n");
      out.write("                                    </small>\r\n");
      out.write("                                    <div id=\"slider2\" class=\"sliders\" style=\"width: 300px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- 월세 끝 -->\r\n");
      out.write("                                <!-- 매매가 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--\r\n");
      out.write("                                <div class=\"modal-header\">\r\n");
      out.write("                                    <h3 class=\"modal-title\">매매가</h3>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"modal-body\" >\r\n");
      out.write("                                    <small style=\"width: 180px;\">\r\n");
      out.write("                                        <div id=\"slider3value1\" class=\"value\"></div> 억원 ~\r\n");
      out.write("                                        <div id=\"slider3value2\" class=\"value\"></div>&nbsp;&nbsp; 억원\r\n");
      out.write("                                    </small>\r\n");
      out.write("                                    <div id=\"slider3\" class=\"sliders\" style=\"width: 300px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t-->\r\n");
      out.write("                                <!-- 매매가 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"modal-footer\" style=\"margin-top: 40px;\">\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-success\" id=\"price\" data-dismiss=\"modal\">적용</button>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- modal 끝 -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- price 끝 -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- detail-search 시작 -->\r\n");
      out.write("            <div class=\"panel-group\" id=\"accordion\" style=\"clear: both; border-bottom: 5px solid #486BB8;\">\r\n");
      out.write("                <div class=\"panel\">\r\n");
      out.write("                    <!-- panel-heading 시작 -->\r\n");
      out.write("                    <div class=\"panel-heading btn-detail\">\r\n");
      out.write("                        <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse1\" style=\"color: #444; font-size: 1.1em;\">\r\n");
      out.write("                            상세 검색&nbsp;&nbsp;<i class=\"fas fa-sort-down\" style=\"color: #486BB8;\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- panel-heading 끝 -->\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"collapse1\" class=\"panel-collapse collapse\">\r\n");
      out.write("                        <!-- panel-body 시작 -->\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("                            <!-- 상세 검색 스위치 시작 -->\r\n");
      out.write("                            <div class=\"row detail well well-sm\" style=\"box-shadow: none;\">\r\n");
      out.write("                                <div class=\"col-md-4 well-detail\">\r\n");
      out.write("                                    <label for=\"parking\">주차가능</label><input type=\"checkbox\" class=\"js-switch js-check-change\"\r\n");
      out.write("                                        id=\"parkingFlag\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-4 well-detail\">\r\n");
      out.write("                                    <label for=\"elevator\">엘리베이터</label><input type=\"checkbox\" class=\"js-switch js-check-change\"\r\n");
      out.write("                                        id=\"elevator\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-4 well-detail\">\r\n");
      out.write("                                    <label for=\"pet\">반려동물</label><input type=\"checkbox\" class=\"js-switch js-check-change\" id=\"pet\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- 상세 검색 스위치 끝 -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- panel-body 끝 -->\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- detail-search 끝 -->\r\n");
      out.write("            <div class=\"search-text\">\r\n");
      out.write("            <hr>\r\n");
      out.write("            \t<!--\r\n");
      out.write("            \t<input type=\"text\" name=\"search\" id=\"search\" class=\"form-control\" value=\"\" placeholder=\"리스트 내 검색 ex) 동 이름, 학교 이름, 역 이름\"  style=\"font-size: 1.2em;\">\r\n");
      out.write("            \t<button type=\"submit\" class=\"form-control\" style=\"display: inline-block; text-align: center; padding: 3px; width: 35px; height: 35px; font-size: 1em;background-color: #486BB8; color: #EEE; outline: none; border-radius: 50%;\">\r\n");
      out.write("            \t<i class=\"fas fa-search\"></i>\r\n");
      out.write("            \t</button>\r\n");
      out.write("            \t  -->\r\n");
      out.write("            </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            <!-- form 태그 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- search-box 끝 -->\r\n");
      out.write("\r\n");
      out.write("            <!-- map 시작 -->\r\n");
      out.write("\t\t\t<div id=\"map\" style=\"width:100%;height:600px;\"></div>\r\n");
      out.write("            <!-- map 끝 -->\r\n");
      out.write("            \r\n");
      out.write("           \t<input type=\"hidden\" id=\"send\" name=\"send\">\r\n");
      out.write("           \t<input type=\"hidden\" id=\"mapping\" name=\"mapping\">\r\n");
      out.write("           \t<input type=\"hidden\" id=\"hide-markers\" name=\"hide-markers\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- list-container 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer 가져오기######## -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.footer-cklee .container{margin:auto;}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"footer-cklee\">\r\n");
      out.write("\t\r\n");
      out.write("\t<p class=\"p-link\">\r\n");
      out.write("\t\t<a href=\"#\">회사소개</a>\r\n");
      out.write("\t\t|<a href=\"#\">이용약관</a>\r\n");
      out.write("\t\t|<a href=\"#\">개인정보처리방침</a>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f9(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p class=\"navbar-text\" id=\"footer-text\">상호 : (주)쌍용방  |  대표 : 김진방<br>\r\n");
      out.write("주소 : 서울특별시 강남구 역삼동 735-1(역삼동, 한독빌딩)<br>\r\n");
      out.write("개인정보처리담당관 : 이다반<br>\r\n");
      out.write("서비스 이용문의 : 02-7668-8048  |  이메일 : cjddpf@sybang.com  |  서비스제휴문의 : partnership@sybang.com</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div> <!-- container-fluid -->\r\n");
      out.write("\t</nav> <!-- navbar -->\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=950df7fcc5aace4db5b109e8c92b5034&libraries=services\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=950df7fcc5aace4db5b109e8c92b5034\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"/sybang/js/address.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//############ 카카오맵 API 변수 선언 및 초기화 시작 ############\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar container = document.getElementById('map');\r\n");
      out.write("\t\tvar options = {\r\n");
      out.write("\t\t\tcenter : new kakao.maps.LatLng(37.499426242183034, 127.03425370768977),\r\n");
      out.write("\t\t\tlevel : 3\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar map = new kakao.maps.Map(container, options);\r\n");
      out.write("\t\tvar geocoder = new kakao.maps.services.Geocoder();\r\n");
      out.write("\t\tvar markers = [];\r\n");
      out.write("\r\n");
      out.write("\t\tfunction setMarkers(map) {\r\n");
      out.write("\t\t    for (var i = 0; i < markers.length; i++) {\r\n");
      out.write("\t\t        markers[i].setMap(map);\r\n");
      out.write("\t\t    }            \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#hide-markers\").click(function hideMarkers() {\r\n");
      out.write("\t\t    setMarkers(null); \r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//############ 카카오맵 API 변수 선언 및 초기화 끝 ############\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//############ 조건 검색 변수 선언 및 초기화 시작 #############\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar where = \"\";\r\n");
      out.write("\t\tvar wheredType = \"\"; //\"and dType in ('temp', '월세', '전세', '매매')\"\r\n");
      out.write("\t\tvar wherebType = \"\";\r\n");
      out.write("\t\tvar whereRoomNum = \"\";\r\n");
      out.write("\t\tvar whereParkingFlag = \"\";\r\n");
      out.write("\t\tvar whereElevator = \"\";\r\n");
      out.write("\t\tvar wherePet = \"\";\r\n");
      out.write("\t\tvar whereAddress = \"\";\r\n");
      out.write("\t\tvar whereArea = \"\";\r\n");
      out.write("\t\tvar wherePrice = \"\";\r\n");
      out.write("\t\tvar whereRent = \"\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#send\").click(function() {\r\n");
      out.write("\t\t\twhere = \"where seq > 0\" + \" \" + wheredType \r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + wherebType\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + whereParkingFlag\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + whereElevator\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + wherePet\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + whereRoomNum\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + whereAddress\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + whereArea\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + wherePrice\r\n");
      out.write("\t\t\t\t\t\t\t\t\t+ \" \" + whereRent;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif (where.trim() == \"where seq > 0\") {\r\n");
      out.write("\t\t\t\twhere = \"where seq < 0\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"input[type=checkbox]\").parent().mouseover(function() {\r\n");
      out.write("\t\t\t$(this).children().eq(0).addClass(\"chosen\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"input[type=checkbox]\").parent().mouseleave(function() {\t\r\n");
      out.write("\t\t\t$(this).children().eq(0).removeClass(\"chosen\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//입력 받은 조건으로 맵에 마커를 띄웁니다.\r\n");
      out.write("\t\t$(\"#mapping\").click(function() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"GET\",\r\n");
      out.write("\t\t\t\turl: \"/sybang/house/searchjsondata.do\",\r\n");
      out.write("\t\t\t\tdata: \"whereSearch=\" + encodeURIComponent(where),\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//result -> {\"name\":\"홍길동\", \"age\":\"20\", \"address\":\"서울\"}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(result).each(function(index, item) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif (item.seq != 0) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tvar roomLocation = item.address;\r\n");
      out.write("\t\t\t\t\t\t\t// 주소로 좌표를 검색합니다\r\n");
      out.write("\t\t\t\t\t\t\tgeocoder.addressSearch(roomLocation, function(result, status) {\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t    // 정상적으로 검색이 완료됐으면 \r\n");
      out.write("\t\t\t\t\t\t\t     if (status === kakao.maps.services.Status.OK) {\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t        var coords = new kakao.maps.LatLng(result[0].y, result[0].x);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t        // 결과값으로 받은 위치를 마커로 표시합니다\r\n");
      out.write("\t\t\t\t\t\t\t        var marker = new kakao.maps.Marker({\r\n");
      out.write("\t\t\t\t\t\t\t            map: map,\r\n");
      out.write("\t\t\t\t\t\t\t            position: coords\r\n");
      out.write("\t\t\t\t\t\t\t        });\r\n");
      out.write("\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t        //마커를 배열에 추가합니다.\r\n");
      out.write("\t\t\t\t\t\t\t        markers.push(marker);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t    // 마커를 클릭했을 때 마커 위에 표시할 인포윈도우를 생성합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t    var iwContent = '<div style=\"padding:5px;\" class=\"infowindow\">' + item.priceTag + '<br>' + item.bType + '<br>' + '<a href=\"/sybang/house/houseview.do?seq=' + item.seq + '\" target=\"_blank\">자세히 보기</a></div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t        iwRemoveable = true; // removeable 속성을 ture 로 설정하면 인포윈도우를 닫을 수 있는 x버튼이 표시됩니다\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t    // 인포윈도우를 생성합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t    var infowindow = new kakao.maps.InfoWindow({\r\n");
      out.write("\t\t\t\t\t\t\t\t        content : iwContent,\r\n");
      out.write("\t\t\t\t\t\t\t\t        removable : iwRemoveable\r\n");
      out.write("\t\t\t\t\t\t\t\t    });\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t    // 마커에 클릭이벤트를 등록합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t    kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t          // 마커 위에 인포윈도우를 표시합니다\r\n");
      out.write("\t\t\t\t\t\t\t\t          infowindow.open(map, marker);  \r\n");
      out.write("\t\t\t\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\t\t     }\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(a,b,c) {\r\n");
      out.write("\t\t\t\t\tconsole.log(a,b,c);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//############ 조건 검색 변수 선언 및 초기화 끝 #############\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//################## 조건별 검색 누적 시작 ##################\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//##### 거래 형태 조건 선택 시작 #####\r\n");
      out.write("\t\t$(\"#dType\").children().change(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//1. 조건 문자열 초기화 및 누적변수 생성\r\n");
      out.write("\t\t\twheredType = \"and dType in ('temp'\";\r\n");
      out.write("\t\t\tlet temp = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//2. 선택한 조건 누적\r\n");
      out.write("\t\t\tif (!$(this).hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttemp += \", '\" + $(this).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (let i=0; i<$(\"#dType\").children().length; i++) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif ($(\"#dType\").children().eq(i).hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttemp += \", '\" + $(\"#dType\").children().eq(i).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\twheredType += temp + \")\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t//3. 조건 검색 실행\r\n");
      out.write("\t\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\troomLocation = \"\";\r\n");
      out.write("\t\t\t\tlet selCount = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (let i=0; i<$(\"#dType\").children().length; i++) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif ($(\"#dType\").children().eq(i).hasClass(\"active\") && \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#dType\").children().eq(i).index() != $(this).index()) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttemp += \", '\" + $(\"#dType\").children().eq(i).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tselCount++;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (selCount == 0) {\r\n");
      out.write("\t\t\t\t\twheredType = \"\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\twheredType += temp + \")\";\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tselCount = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//##### 거래 형태 조건 선택 끝 #####\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//##### 건물 형태 조건 선택 시작 #####\r\n");
      out.write("\t\t$(\"#bType\").children().change(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//1. 조건 문자열 초기화 및 누적변수 생성\r\n");
      out.write("\t\t\twherebType = \"and bType in ('temp'\";\r\n");
      out.write("\t\t\tlet temp = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//2. 선택한 조건 누적\r\n");
      out.write("\t\t\tif (!$(this).hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttemp += \", '\" + $(this).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (let i=0; i<$(\"#bType\").children().length; i++) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif ($(\"#bType\").children().eq(i).hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttemp += \", '\" + $(\"#bType\").children().eq(i).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\twherebType += temp + \")\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t//3. 조건 검색 실행\r\n");
      out.write("\t\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\troomLocation = \"\";\r\n");
      out.write("\t\t\t\tlet selCount = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (let i=0; i<$(\"#bType\").children().length; i++) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif ($(\"#bType\").children().eq(i).hasClass(\"active\") && \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#bType\").children().eq(i).index() != $(this).index()) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttemp += \", '\" + $(\"#bType\").children().eq(i).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tselCount++;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (selCount == 0) {\r\n");
      out.write("\t\t\t\t\twherebType = \"\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\twherebType += temp + \")\";\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tselCount = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//##### 건물 형태 조건 선택 끝 #####\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//##### 방 개수 조건 선택 시작 #####\r\n");
      out.write("\t\t$(\"#roomNum\").children().change(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//1. 조건 문자열 초기화 및 누적변수 생성\r\n");
      out.write("\t\t\twhereRoomNum = \"and roomNum in ('0'\";\r\n");
      out.write("\t\t\tlet temp = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//2. 선택한 조건 누적\r\n");
      out.write("\t\t\tif (!$(this).hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\ttemp += \", '\" + $(this).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (let i=0; i<$(\"#roomNum\").children().length; i++) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif ($(\"#roomNum\").children().eq(i).hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttemp += \", '\" + $(\"#roomNum\").children().eq(i).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\twhereRoomNum += temp + \")\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//3. 조건 검색 실행\r\n");
      out.write("\t\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\troomLocation = \"\";\r\n");
      out.write("\t\t\t\tlet selCount = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (let i=0; i<$(\"#roomNum\").children().length; i++) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif ($(\"#roomNum\").children().eq(i).hasClass(\"active\") && \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#roomNum\").children().eq(i).index() != $(this).index()) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttemp += \", '\" + $(\"#roomNum\").children().eq(i).children().eq(0).val() + \"'\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tselCount++;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (selCount == 0) {\r\n");
      out.write("\t\t\t\t\twhereRoomNum = \"\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\twhereRoomNum += temp + \")\";\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tselCount = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//##### 방 개수 조건 선택 끝 #####\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//##### 상세 검색 조건 선택 시작 ######\r\n");
      out.write("\t\tvar changeCheckbox = document.querySelectorAll('.js-check-change')\r\n");
      out.write("\r\n");
      out.write("\t\tchangeCheckbox[0].onchange = function() {\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\tif(changeCheckbox[0].checked) {\r\n");
      out.write("  \t\t\t\twhereParkingFlag = \"and parkingFlag = '가능'\"\r\n");
      out.write("  \t\t\t} else {\r\n");
      out.write("  \t\t\t\twhereParkingFlag = \"\";\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t$(\"#mapping\").click();\r\n");
      out.write("  \t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchangeCheckbox[1].onchange = function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(changeCheckbox[1].checked) {\r\n");
      out.write("  \t\t\t\twhereElevator = \"and elevator = '있음'\"\r\n");
      out.write("  \t\t\t} else {\r\n");
      out.write("  \t\t\t\twhereElevator = \"\";\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tchangeCheckbox[2].onchange = function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tif(changeCheckbox[2].checked) {\r\n");
      out.write("  \t\t\t\twherePet = \"and pet = '가능'\"\r\n");
      out.write("  \t\t\t} else {\r\n");
      out.write("  \t\t\t\twherePet = \"\";\r\n");
      out.write("  \t\t\t}\r\n");
      out.write("  \t\t\t\r\n");
      out.write("  \t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t//##### 상세 검색 조건 선택 끝 ######\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//##### 지역 조건 선택 시작 ######\r\n");
      out.write("\t\t$('#sido').change(function() {\r\n");
      out.write("    \t\twhereAddress = \"and address like '%%\" + $(this).val() + \"%%' \"\r\n");
      out.write("    \t\t+ \"and address like '%%\" + $(this).siblings().eq(1).val() + \"%%' \" \r\n");
      out.write("    \t\t+ \"and address like '%%\" + $(this).siblings().eq(2).val() + \"%%' \"\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tif ($(this).val() + $(this).siblings().eq(1).val() + $(this).siblings().eq(2).val() == \"\") {\r\n");
      out.write("    \t\t\twhereAddress = \"\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#gungoo').change(function() {\r\n");
      out.write("\t\t\twhereAddress = \"and address like '%%\" + $(this).val() + \"%%' \"\r\n");
      out.write("\t\t\t+ \"and address like '%%\" + $(this).siblings().eq(1).val() + \"%%' \" \r\n");
      out.write("\t\t\t+ \"and address like '%%\" + $(this).siblings().eq(2).val() + \"%%' \"\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($(this).val() + $(this).siblings().eq(1).val() + $(this).siblings().eq(2).val() == \"\") {\r\n");
      out.write("    \t\t\twhereAddress = \"\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#dong').change(function() {\r\n");
      out.write("\t\t\twhereAddress = \"and address like '%%\" + $(this).val() + \"%%' \"\r\n");
      out.write("\t\t\t+ \"and address like '%%\" + $(this).siblings().eq(1).val() + \"%%' \" \r\n");
      out.write("\t\t\t+ \"and address like '%%\" + $(this).siblings().eq(2).val() + \"%%' \"\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($(this).val() + $(this).siblings().eq(1).val() + $(this).siblings().eq(2).val() == \"\") {\r\n");
      out.write("    \t\t\twhereAddress = \"\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//##### 지역 조건 선택 끝 ######\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//##### 면적 조건 선택 시작 ######\r\n");
      out.write("\t\t$(\"#area\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\twhereArea = \"and exclusiveArea between \" + $(this).parent().prev().find(\"#slider0value1\").text() + \" and \" + $(this).parent().prev().find(\"#slider0value2\").text();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($(this).parent().prev().find(\"#slider0value1\").text() == \"\" || $(this).parent().prev().find(\"#slider0value2\").text() == \"\") {\r\n");
      out.write("    \t\t\twhereArea = \"\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//##### 면적 조건 선택 끝 ######\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//##### 가격 조건 선택 시작 ######\r\n");
      out.write("\t\t$(\"#price\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\twherePrice = \"and price between \" + $(\"#slider1value1\").text() + \" and \" + $(\"#slider1value2\").text();\r\n");
      out.write("\t\t\twhereRent = \"and rent between \" + $(\"#slider2value1\").text() + \" and \" + $(\"#slider2value2\").text();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($(\"#slider1value1\").text() == \"\" || $(\"#slider1value2\").text() == \"\") {\r\n");
      out.write("    \t\t\twherePrice = \"\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($(\"#slider2value1\").text() == \"\" || $(\"#slider2value2\").text() == \"\") {\r\n");
      out.write("    \t\t\twhereRent = \"\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#hide-markers\").click();\r\n");
      out.write("\t\t\t$(\"#send\").click(); //현재까지 선택된 조건을 var where에 취합\r\n");
      out.write("\t\t\t$(\"#mapping\").click();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//##### 가격 조건 선택 끝 ######\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//################## 조건별 검색 누적 끝 ##################\r\n");
      out.write("\t\t\r\n");
      out.write("\t\twindow.onload = function() {\r\n");
      out.write("\t\t\t$(\"#search\").focus();\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar elems = Array.prototype.slice.call(document\r\n");
      out.write("\t\t\t\t.querySelectorAll('.js-switch'));\r\n");
      out.write("\r\n");
      out.write("\t\telems.forEach(function(html) {\r\n");
      out.write("\t\t\tvar switchery = new Switchery(html, { color: '#486DBE', jackColor: '#D6EFF8' });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#slider0\").slider({\r\n");
      out.write("\r\n");
      out.write("            range: true,\r\n");
      out.write("            min: 16,\r\n");
      out.write("            max: 115,\r\n");
      out.write("            values: [16, 115],\r\n");
      out.write("            step: 1,\r\n");
      out.write("            slide: function (event, ui) {\r\n");
      out.write("                $(\"#slider0value1\").text(ui.values[0]);\r\n");
      out.write("                $(\"#slider0value2\").text(ui.values[1]);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#slider1\").slider({\r\n");
      out.write("\r\n");
      out.write("            range: true,\r\n");
      out.write("            min: 0,\r\n");
      out.write("            max: 500000,\r\n");
      out.write("            values: [0, 10000],\r\n");
      out.write("            step: 1,\r\n");
      out.write("            slide: function (event, ui) {\r\n");
      out.write("                $(\"#slider1value1\").text(ui.values[0]);\r\n");
      out.write("                $(\"#slider1value2\").text(ui.values[1]);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#slider2\").slider({\r\n");
      out.write("\r\n");
      out.write("            range: true,\r\n");
      out.write("            min: 1,\r\n");
      out.write("            max: 1000,\r\n");
      out.write("            values: [50, 1000],\r\n");
      out.write("            step: 1,\r\n");
      out.write("            slide: function (event, ui) {\r\n");
      out.write("                $(\"#slider2value1\").text(ui.values[0]);\r\n");
      out.write("                $(\"#slider2value2\").text(ui.values[1]);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("\t\t/*\r\n");
      out.write("        $(\"#slider3\").slider({\r\n");
      out.write("\r\n");
      out.write("            range: true,\r\n");
      out.write("            min: 0,\r\n");
      out.write("            max: 1000,\r\n");
      out.write("            values: [0, 10],\r\n");
      out.write("            step: 1,\r\n");
      out.write("            slide: function (event, ui) {\r\n");
      out.write("                $(\"#slider3value1\").text(ui.values[0]);\r\n");
      out.write("                $(\"#slider3value2\").text(ui.values[1]);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\t\t*/\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/header.jsp(30,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty email }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/inquiry/list.do\">문의게시판</a></li>\r\n");
          out.write("\t\t\t\t            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(37,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty email && access == 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t          \t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/brokerMain.do\">내 프로필</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/room/list.do\">방 조회/매물 등록하기</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/house/myreglist.do\">내가 등록한 매물</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/ad/payment.do\">광고</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/chat/chatlist.do\">구매자와 상담하기</a></li>\r\n");
          out.write("\t\t\t\t            <li class=\"divider\"></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/hope/hopelist.do\">희망 매물 조회하기</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/review/reviewlist.do\">후기/평점 조회하기</a></li>\r\n");
          out.write("\t\t\t         \t</ul>\r\n");
          out.write("\t\t\t         \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/inc/header.jsp(53,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty email}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t          \t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/service/servicemain.do\">청소/시공업체 홈</a></li>\t\t\t          \t\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/service/ServicestoreList.do\">전문업체 찾기</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/request/requestlist.do\">고객요청서</a></li>\r\n");
          out.write("\t\t\t\t            <li class=\"divider\"></li>\r\n");
          out.write("\t\t\t\t\t        \r\n");
          out.write("\t\t\t\t\t        <!-- 업체 로그인시 업체쪽에서 보일 채팅창리스트-->\r\n");
          out.write("\t\t\t\t\t        ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t        <!-- 회원 로그인시 회원 쪽에서 보일 채팅창리스트-->\r\n");
          out.write("\t\t\t\t\t        ");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t        \r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/servicereview/servicereview.do\">후기</a></li>\r\n");
          out.write("\t\t\t\t            <li class=\"divider\"></li>\r\n");
          out.write("\t\t\t\t            ");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t         \t</ul>\r\n");
          out.write("\t\t\t         \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/inc/header.jsp(61,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == '2' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t        <li><a href=\"/sybang/servicechat/partnerlist.do\">1:1 문의</a></li>\r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/inc/header.jsp(65,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == '1' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t\t\t\t        <li><a href=\"/sybang/servicechat/memberspartnerlist.do\">1:1 문의</a></li>\r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/inc/header.jsp(71,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 업체로 로그인 시 보이는 메뉴 -->\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/service/servicemypage.do\">마이 서비스</a></li>\r\n");
          out.write("\t\t\t\t           \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /WEB-INF/views/inc/header.jsp(81,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty email }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        \t\t\t<li><a href=\"/sybang/login/loginbuttons.do\" style=\"font-size: 1.3em;\">로그인</a></li>\r\n");
          out.write("        \t\t\t<li><a href=\"#\" style=\"font-size: 1.3em;\">회원가입</a></li>\r\n");
          out.write("        \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/views/inc/header.jsp(87,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty email }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        \t\t\t");
          if (_jspx_meth_c_005fif_005f8(_jspx_th_c_005fif_005f7, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\r\n");
          out.write("        \t\t\t<li><a href=\"/sybang/member/logout.do\" style=\"font-size: 1.3em;\">로그아웃</a></li>\r\n");
          out.write("        \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f7);
      // /WEB-INF/views/inc/header.jsp(88,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        \t\t\t<li class=\"dropdown\">\r\n");
          out.write("          \t\t\t<a href=\"/sybang/member/mypage.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\" style=\"font-size: 1.3em;\">마이페이지<span class=\"caret\"></span></a>\r\n");
          out.write("\t\t\t          \t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/member/myinfo.do\" style=\"font-size: 1.1em;\">내 정보 관리</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"#\" style=\"font-size: 1.1em;\">스케줄러</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"#\" style=\"font-size: 1.1em;\">1:1 문의 내역</a></li>\r\n");
          out.write("\t\t\t         \t</ul>\r\n");
          out.write("        \t\t\t</li>\r\n");
          out.write("        \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f9_reused = false;
    try {
      _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f9.setParent(null);
      // /WEB-INF/views/inc/footer.jsp(13,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
      if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t|<a href=\"/sybang/admin/index.do\">관리자 메뉴</a>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
      _jspx_th_c_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f9_reused);
    }
    return false;
  }
}
