/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.61
 * Generated at: 2021-03-03 00:09:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/project/SsangYongBangProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/SsangYongBang/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1613534080129L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1614730153150L));
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1614146715570L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1613455475942L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>내 정보 관리</title>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sybang/asset/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sybang/css/main.css\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/sybang/images/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"/sybang/asset/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"/sybang/asset/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/sybang/css/mypage.css\">\r\n");
      out.write("<style>\r\n");
      out.write(".page-bar {\r\n");
      out.write("\tmargin-left: 200px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-container {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    width: 1000px;\r\n");
      out.write("    margin: 30px auto;\r\n");
      out.write("    height: 1050px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".off {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#writecomment #nav,\r\n");
      out.write("#writereview #nav {\r\n");
      out.write("  width: 500px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#writecomment #nav a,\r\n");
      out.write("#writereview #nav a {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  color: #3B79BC;\r\n");
      out.write("  width: 35px;\r\n");
      out.write("  height: 35px;\r\n");
      out.write("  padding: 6px;\r\n");
      out.write("  border: 1px solid #EEE;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#writecomment #nav a.active,\r\n");
      out.write("#writereview #nav a.active {\r\n");
      out.write("  background: #3B79BC;\r\n");
      out.write("  color: #EEE;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- header 가져오기######## -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t/* house.css와 width, padding 충돌 */\r\n");
      out.write("\t.header-cklee .dropdown, .dropdown-menu {\r\n");
      out.write("\t    width: auto;\r\n");
      out.write("\t    padding: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-cklee\">\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-static-top\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"/sybang/index.do\">\r\n");
      out.write("\t\t\t\t<img alt=\"Brand\" src=\"/sybang/images/logo.png\" id=\"logo\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"/sybang/index.do\">홈</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/sybang/house/search.do\">방찾기</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/sybang/hope/post.do\">희망입주하기</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/sybang/house/post.do\">방내놓기</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">커뮤니티<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t          \t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t            <li><a href=\"/sybang/notice/list.do\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t            <li><a href=\"/sybang/free/list.do\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t         \t</ul>\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"/sybang/broker/brokerMain.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">중개사공간<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t          \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("          \t\t\t<a href=\"/sybang/service/servicemain.do\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">청소/시공<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t          \t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\t</li>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t<!-- 로그인 전 -->\r\n");
      out.write("        \t\t\t");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t\t<!-- 로그인 후 -->\r\n");
      out.write("        \t\t\t");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> <!-- container-fluid -->\r\n");
      out.write("\t</nav> <!-- navbar -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {    \r\n");
      out.write("\t  $('.navbar-default .navbar-nav > li.dropdown').hover(function() {\r\n");
      out.write("\t\t$('ul.dropdown-menu', this).stop(true, true).slideDown('fast');\r\n");
      out.write("\t\t$(this).addClass('open');\r\n");
      out.write("\t  }, function() {\r\n");
      out.write("\t\t$('ul.dropdown-menu', this).stop(true, true).slideUp('fast');\r\n");
      out.write("\t\t$(this).removeClass('open');\r\n");
      out.write("\t  });\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- list-container 시작 -->\r\n");
      out.write("    <div class=\"list-container\" style=\"margin-top: -50px;\">\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <h1>내 정보 관리</h1>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"myinfo-container well\">\r\n");
      out.write("                <table class=\"table\" id=\"myinfo\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td rowspan=\"2\"><img src=\"/sybang/images/nopic.jpg\" height=\"100px;\"></td>\r\n");
      out.write("                        <td style=\"font-size: 1.3em;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</td>\r\n");
      out.write("                        <td rowspan=\"2\"><a href=\"/sybang/member/changeinfo.do\" class=\"btn btn-default\" value=\"\"\r\n");
      out.write("                            style=\"font-size: 1.1em; text-align: center; margin-top: 25px;\">내 정보 수정</a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>\r\n");
      out.write("                            총 게시물&nbsp;&nbsp;<strong style=\"color: #3777BA;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>개\r\n");
      out.write("                            / 총 댓글&nbsp;&nbsp;<strong style=\"color: #3777BA;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalComment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>개\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"nav nav-tabs\" style=\"clear: both;\">\r\n");
      out.write("            <li class=\"active\"><a data-toggle=\"tab\" id=\"myPost\" href=\"#writepost\">내가 쓴 글</a></li>\r\n");
      out.write("            <li><a data-toggle=\"tab\" id=\"myComment\" href=\"#writecomment\">내가 쓴 댓글</a></li>\r\n");
      out.write("            <li><a data-toggle=\"tab\" id=\"myReview\" href=\"#writereview\">내 후기/평점</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <!-- tab-content 시작 -->\r\n");
      out.write("        <div class=\"tab-content\">\r\n");
      out.write("\r\n");
      out.write("            <!-- 내가 쓴 글 시작 -->\r\n");
      out.write("            <div class=\"tab-pane fade in active\" id=\"writepost\">\r\n");
      out.write("            \t<div id=\"btn-post\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\" id=\"ckAll\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-ok\"></span> 전체 선택\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-trash\"></span> 삭제\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"clear: both;\"></div>\r\n");
      out.write("                <table class=\"table table-condensed\" id=\"tbl-post\">\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th></th>\r\n");
      out.write("                        <th>번호</th>\r\n");
      out.write("                        <th>제목</th>\r\n");
      out.write("                        <th>작성일</th>\r\n");
      out.write("                        <th>조회수</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 받아온 내가 쓴 글 목록을 forEach로  -->\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("                <!-- page-bar 시작 -->\r\n");
      out.write("\t\t\t\t<nav class=\"col-md-8 page-bar\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"pagination\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ppagebar }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- page-bar 끝 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 내가 쓴 글 끝 -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 내가 쓴 댓글 시작 -->\r\n");
      out.write("            <div class=\"tab-pane fade\" id=\"writecomment\">\r\n");
      out.write("            <div id=\"btn-comment\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-ok\"></span> 전체 선택\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\">\r\n");
      out.write("                            <span class=\"glyphicon glyphicon-trash\"></span> 삭제\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div style=\"clear: both;\"></div>\r\n");
      out.write("                <table class=\"table table-condensed\" id=\"tblcomment\">\r\n");
      out.write("                \t<thead>\r\n");
      out.write("                \t</thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("\t                    \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 내가 쓴 댓글 끝 -->\r\n");
      out.write("\r\n");
      out.write("            <!-- 내 후기 시작 -->\r\n");
      out.write("            <div class=\"tab-pane\" id=\"writereview\">\r\n");
      out.write("                <table class=\"table table-condensed\" id=\"tblreview\">\r\n");
      out.write("                \t<thead>\r\n");
      out.write("\t                    <tr>\r\n");
      out.write("\t                        <th class=\"col-md-3\">중개사</th>\r\n");
      out.write("\t                        <th class=\"col-md-2\">평점</th>\r\n");
      out.write("\t                        <th class=\"col-md-5\">후기</th>\r\n");
      out.write("\t                        <th class=\"col-md-2\">작성일</th>\r\n");
      out.write("\t                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("\t                    \r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 내 후기 끝 -->\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- tab-content 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- list-container 끝 -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- footer 가져오기######## -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.footer-cklee .container{margin:auto;}\r\n");
      out.write("</style>\r\n");
      out.write("<div class=\"footer-cklee\">\r\n");
      out.write("\t\r\n");
      out.write("\t<p class=\"p-link\">\r\n");
      out.write("\t\t<a href=\"#\">회사소개</a>\r\n");
      out.write("\t\t|<a href=\"#\">이용약관</a>\r\n");
      out.write("\t\t|<a href=\"#\">개인정보처리방침</a>\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f12(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<p class=\"navbar-text\" id=\"footer-text\">상호 : (주)쌍용방  |  대표 : 김진방<br>\r\n");
      out.write("주소 : 서울특별시 강남구 역삼동 735-1(역삼동, 한독빌딩)<br>\r\n");
      out.write("개인정보처리담당관 : 이다반<br>\r\n");
      out.write("서비스 이용문의 : 02-7668-8048  |  이메일 : cjddpf@sybang.com  |  서비스제휴문의 : partnership@sybang.com</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div> <!-- container-fluid -->\r\n");
      out.write("\t</nav> <!-- navbar -->\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#ckAll\").click(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ($(\".ckItem\").prop(\"checked\")) {\r\n");
      out.write("\t\t\t\t$(\".ckItem\").prop(\"checked\", false);\t\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\".ckItem\").prop(\"checked\", true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t//내가 쓴 댓글 클릭 시\r\n");
      out.write("\t\t$(\"#myComment\").click(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"GET\",\r\n");
      out.write("\t\t\t\turl: \"/sybang/member/mycommentdata.do\",\r\n");
      out.write("\t\t\t\tdata: \"authorseq=\" + ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tasync: false,\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t$(\"#tblcomment tbody\").html(\"\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(result).each(function(index, item) {\r\n");
      out.write("\t\t\t\t\t\tlet temp = \"\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<tr onclick=\\\"location.href=\\'/sybang/free/detail.do?seq=\" + item.frseq + \"\\';\\\">\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<td><input type=\\\"checkbox\\\"></td>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<td><div class=\\\"cmt-date\\\">\" + item.regdate + \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t//temp += \"<c\\:if test=\\\"\" + item.gap \"< 1\\\"><span class=\\\"badge\\\" style=\\\"background-color: red\\;\\\">N</span></c\\:if>;\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<div class=\\\"cmt-content\\\">\" + item.detail + \"</div>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<div class=\\\"cmt-title\\\">원문 제목 : \" + item.subject +\"</div>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"</td>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#tblcomment tbody\").append(temp);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(a, b, c) {\r\n");
      out.write("\t\t\t\t\talert(\"가져올 댓글이 없습니다.\");\r\n");
      out.write("\t\t\t\t\tconsole.log(a, b, c);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t//내가 쓴 댓글 페이징\r\n");
      out.write("\t\t$(\"#myComment\").click(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#nav\").remove();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#tblcomment\").after(\"<div class=\\\"col-md-12 page-bar\\\" id=\\\"nav\\\">\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//총 개수\r\n");
      out.write("\t\t\tvar rowtotal = $(\"#tblcomment\").find(\"tr\").length;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//총 페이지 수\r\n");
      out.write("\t\t\tvar total = Math.ceil(rowtotal/5);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar i = 0;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfor (; i < total; i++){\r\n");
      out.write("\t\t\t\t$(\"<a class=\\\"pagination\\\" href=\\\"#\\\"></a>\").attr(\"rel\", i).html(i+1).appendTo(\"#nav\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#tblcomment\").find(\"tr\").addClass(\"off\").slice(0, 5).removeClass(\"off\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar link = $(\"#nav a\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlink.on(\"click\", function(evt) {\r\n");
      out.write("\t\t\t\tevt.preventDefault();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif ($(this).hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tlink.removeClass(\"active\");\r\n");
      out.write("\t\t\t\t$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar nowPage = $(this).attr(\"rel\");\r\n");
      out.write("\t\t\t\tvar begin = nowPage * 5;\r\n");
      out.write("\t\t\t\tvar end = begin + 5;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#tblcomment\").find(\"tr\").css(\"opacity\", \"0\").addClass(\"off\").slice(begin, end).removeClass(\"off\").animate({opacity: 1}, 300);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlink.filter(\":first\").addClass(\"active\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//내 후기 클릭 시\r\n");
      out.write("\t\t$(\"#myReview\").click(function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype: \"GET\",\r\n");
      out.write("\t\t\t\turl: \"/sybang/member/myreviewdata.do\",\r\n");
      out.write("\t\t\t\tdata: \"mseq=\" + ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tasync: false,\r\n");
      out.write("\t\t\t\tsuccess: function(result) {\r\n");
      out.write("\t\t\t\t\t$(\"#tblreview tbody\").html(\"\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(result).each(function(index, item) {\r\n");
      out.write("\t\t\t\t\t\tlet temp = \"\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<tr>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<td style=\\\"font-size: 1.1em;\\\">\" + item.bname + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<td style=\\\"font-size: 1.1em; color: #486BB8;\\\">\" + item.star + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<td style=\\\"font-size: 1.1em;\\\">\" + item.detail + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"<td style=\\\"font-size: 1.1em;\\\">\" + item.regdate + \"</td>\";\r\n");
      out.write("\t\t\t\t\t\ttemp += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#tblreview tbody\").append(temp);\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(a, b, c) {\r\n");
      out.write("\t\t\t\t\talert(\"가져올 후기가 없습니다.\");\r\n");
      out.write("\t\t\t\t\tconsole.log(a, b, c);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//내 후기 페이징\r\n");
      out.write("\t\t\t$(\"#myReview\").click(function() {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#nav\").remove();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#tblreview\").after(\"<div class=\\\"col-md-12 page-bar\\\" id=\\\"nav\\\">\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//총 개수\r\n");
      out.write("\t\t\t\tvar rowtotal = $(\"#tblreview tbody\").find(\"tr\").length;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//총 페이지 수\r\n");
      out.write("\t\t\t\tvar total = Math.ceil(rowtotal/5);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar i = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (; i < total; i++){\r\n");
      out.write("\t\t\t\t\t$(\"<a class=\\\"pagination\\\" href=\\\"#\\\"></a>\").attr(\"rel\", i).html(i+1).appendTo(\"#nav\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#tblreview\").find(\"tr\").addClass(\"off\").slice(0, 5).removeClass(\"off\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar link = $(\"#nav a\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlink.on(\"click\", function(evt) {\r\n");
      out.write("\t\t\t\t\tevt.preventDefault();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif ($(this).hasClass(\"active\")) {\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tlink.removeClass(\"active\");\r\n");
      out.write("\t\t\t\t\t$(this).addClass(\"active\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar nowPage = $(this).attr(\"rel\");\r\n");
      out.write("\t\t\t\t\tvar begin = nowPage * 5;\r\n");
      out.write("\t\t\t\t\tvar end = begin + 5;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#tblreview\").find(\"tr\").css(\"opacity\", \"0\").addClass(\"off\").slice(begin, end).removeClass(\"off\").animate({opacity: 1}, 300);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tlink.filter(\":first\").addClass(\"active\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/header.jsp(30,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty email }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/inquiry/list.do\">문의게시판</a></li>\r\n");
          out.write("\t\t\t\t            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(37,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty email && access == 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t          \t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/brokerMain.do\">내 프로필</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/room/list.do\">방 조회/매물 등록하기</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/house/myreglist.do\">내가 등록한 매물</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/ad/payment.do\">광고</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/chat/chatlist.do\">구매자와 상담하기</a></li>\r\n");
          out.write("\t\t\t\t            <li class=\"divider\"></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/hope/hopelist.do\">희망 매물 조회하기</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/broker/review/reviewlist.do\">후기/평점 조회하기</a></li>\r\n");
          out.write("\t\t\t         \t</ul>\r\n");
          out.write("\t\t\t         \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/inc/header.jsp(53,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty email}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t          \t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/service/servicemain.do\">청소/시공업체 홈</a></li>\t\t\t          \t\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/service/ServicestoreList.do\">전문업체 찾기</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/request/requestlist.do\">고객요청서</a></li>\r\n");
          out.write("\t\t\t\t            <li class=\"divider\"></li>\r\n");
          out.write("\t\t\t\t\t        \r\n");
          out.write("\t\t\t\t\t        <!-- 업체 로그인시 업체쪽에서 보일 채팅창리스트-->\r\n");
          out.write("\t\t\t\t\t        ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t        <!-- 회원 로그인시 회원 쪽에서 보일 채팅창리스트-->\r\n");
          out.write("\t\t\t\t\t        ");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t        \r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/servicereview/servicereview.do\">후기</a></li>\r\n");
          out.write("\t\t\t\t            <li class=\"divider\"></li>\r\n");
          out.write("\t\t\t\t            ");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t         \t</ul>\r\n");
          out.write("\t\t\t         \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/inc/header.jsp(61,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == '2' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t        <li><a href=\"/sybang/servicechat/partnerlist.do\">1:1 문의</a></li>\r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/inc/header.jsp(65,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == '1' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("\t\t\t\t\t        <li><a href=\"/sybang/servicechat/memberspartnerlist.do\">1:1 문의</a></li>\r\n");
          out.write("\t\t\t\t\t        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/inc/header.jsp(71,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == 2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 업체로 로그인 시 보이는 메뉴 -->\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/service/servicemypage.do\">마이 서비스</a></li>\r\n");
          out.write("\t\t\t\t           \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /WEB-INF/views/inc/header.jsp(81,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty email }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        \t\t\t<li><a href=\"/sybang/login/loginbuttons.do\" style=\"font-size: 1.3em;\">로그인</a></li>\r\n");
          out.write("        \t\t\t<li><a href=\"#\" style=\"font-size: 1.3em;\">회원가입</a></li>\r\n");
          out.write("        \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/views/inc/header.jsp(87,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty email }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        \t\t\t");
          if (_jspx_meth_c_005fif_005f8(_jspx_th_c_005fif_005f7, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\r\n");
          out.write("        \t\t\t<li><a href=\"/sybang/member/logout.do\" style=\"font-size: 1.3em;\">로그아웃</a></li>\r\n");
          out.write("        \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f7);
      // /WEB-INF/views/inc/header.jsp(88,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        \t\t\t<li>\r\n");
          out.write("          \t\t\t<a href=\"/sybang/member/myinfo.do\" style=\"font-size: 1.3em;\">마이페이지</a>\r\n");
          out.write("\t\t\t          \t<!-- <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
          out.write("\t\t\t\t            <li><a href=\"/sybang/member/myinfo.do\" style=\"font-size: 1.1em;\">내 정보 관리</a></li>\r\n");
          out.write("\t\t\t\t            <li><a href=\"#\" style=\"font-size: 1.1em;\">스케줄러</a></li>\r\n");
          out.write("\t\t\t         \t</ul> -->\r\n");
          out.write("        \t\t\t</li>\r\n");
          out.write("        \t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/member/myinfo.jsp(113,20) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/myinfo.jsp(113,20) '${plist }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${plist }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/member/myinfo.jsp(113,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("pdto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                    <tr>\r\n");
            out.write("                        <td><input type=\"checkbox\" class=\"ckItem\"></td>\r\n");
            out.write("                        <td style=\"font-size: 1.2em;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.seq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t<!-- 해당 글이 자유게시판 글일 경우 -->\r\n");
            out.write("                        ");
            if (_jspx_meth_c_005fif_005f9(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("                        <!-- 해당 글이 문의게시판 글일 경우 -->\r\n");
            out.write("                        ");
            if (_jspx_meth_c_005fif_005f10(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t<!-- 최신 글 시작 -->\r\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fif_005f11(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<!-- 최신 글 끝 -->\r\n");
            out.write("                           \r\n");
            out.write("                            <div class=\"post-content\" style=\"font-size: 0.9em;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.detail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            <div class=\"post-type\" style=\"font-size: 0.8em;\">게시판 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.which }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                        </td>\r\n");
            out.write("                        <td>\r\n");
            out.write("                            <div class=\"post-date\" style=\"font-size: 1.1em;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.regdate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                        </td>\r\n");
            out.write("                        <td>\r\n");
            out.write("                            <div class=\"post-readcount\" style=\"font-size: 1.2em;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.readcount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                        </td>\r\n");
            out.write("                    </tr>\r\n");
            out.write("                    ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f9_reused = false;
    try {
      _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/member/myinfo.jsp(118,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.which eq '자유게시판' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
      if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        \t<td onclick=\"location.href='/sybang/free/detail.do?seq=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("';\" style=\"font-size: 1.2em;\">\r\n");
          out.write("                        \t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.subject }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&nbsp;(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.ccount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
      _jspx_th_c_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f10 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f10_reused = false;
    try {
      _jspx_th_c_005fif_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/member/myinfo.jsp(123,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f10.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.which eq '문의게시판' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f10 = _jspx_th_c_005fif_005f10.doStartTag();
      if (_jspx_eval_c_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                        <td onclick=\"location.href='/sybang/inquiry/detail.do?seq=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("';\" style=\"font-size: 1.2em;\">\r\n");
          out.write("\t                        ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.subject }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&nbsp;(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.ccount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f10.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
      _jspx_th_c_005fif_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f11 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f11_reused = false;
    try {
      _jspx_th_c_005fif_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/member/myinfo.jsp(129,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f11.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pdto.gap < 1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f11 = _jspx_th_c_005fif_005f11.doStartTag();
      if (_jspx_eval_c_005fif_005f11 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<span class=\"badge\" style=\"background-color: red;\">N</span>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f11.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f11);
      _jspx_th_c_005fif_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f11, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f12 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f12_reused = false;
    try {
      _jspx_th_c_005fif_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f12.setParent(null);
      // /WEB-INF/views/inc/footer.jsp(13,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f12.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${access == 3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f12 = _jspx_th_c_005fif_005f12.doStartTag();
      if (_jspx_eval_c_005fif_005f12 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t|<a href=\"/sybang/admin/index.do\">관리자 메뉴</a>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f12.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f12);
      _jspx_th_c_005fif_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f12, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f12_reused);
    }
    return false;
  }
}
